In [ ]:
import numpy as np

input_nums = input("Enter numbers")
nums = []
print(input_nums)
for i in input_nums.split():
    temp = int(i)
    nums.append(temp)

values,count = np.unique(nums, return_counts = True)
print("Values : ", values)
print("Counts : ",count)

Values :  [1 2 3 4 5]
Counts :  [1 2 1 3 1]


In [29]:
import numpy as np

input_nums = input("Enter numbers")
array = np.array(input_nums.split(), dtype=int)

print(array)

count_ones = np.sum(array == 1)
count_zeroes = np.sum(array == 0)

output = '1'*count_ones + '0'*count_zeroes
print(output)
print(array==4)

[1 0 1 4]
110
[False False False  True]


In [30]:
import numpy as np

text = input("Enter a string: ")
n = int(input("Enter the index to remove: "))

# Convert string to NumPy array of characters
char_array = np.array(list(text))

# Remove the character at index n using np.delete
new_array = np.delete(char_array, n)

# Join back into a string
new_text = ''.join(new_array)

print("Result:", new_text)


Result: ABDEF


In [31]:
import numpy as np

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
